print("#!/bin/csh")
print("set dir = ./ss1a2/")
print("set fileinfo = ./ss1a2/info_pr.dat")
print("set filestm = {$dir}ss1_st0.dat")
print("set fileqdi = {$dir}ss1a2qdi.gr")
print("set filew =   {$dir}ss1a2ww.gr")
print("./omegainv.exe << !")
print("'$fileinfo' 	#>>>>>Escribe info file info.dat:")
print("'$fileqdi' 	#>>>>>Escribe fichero de Div Q:")
print("'$filestm'   	#>>>>>Escribe fichero de densidad promedio:")
print("'ominput.dat'  #>>>>>Escribe fichero parametros (ominput.dat):")
print("'$filew'	#>>>>>Escribe fichero Salida W:")
print("!")